target/captains-log

- .example.drone.yml
> chore: Add Example .drone.yml

- docs/configuration/README.md
- docs/examples/README.md
Thanks to @jmccann for spotting this inconsistency. 👍
> Update Docs To Reflect Correct Signature

- docs/contributing/README.md
> chore(spelling): update docs

- src/constants/index.js
- src/index.js
> Add Org/Repo to Default Heading

- src/constants/index.js
- src/index.js
- Changed the `DEFAULT_HEADING` from a template literal to a function, as @AndersDJohnson suggested in #34. 
- Forgot to update empty state in #34 as well, so this should cover that.
> Update Empty State To Include Org/Repo

- src/constants/index.js
- src/index.js
The post will have a consistent look regardless of if we could find any references to jira stories.
(I'm not versed in jest well enough to figure out how to write a test for a `const`.
> Consistent appearance of slack posts

- docs/examples/README.md
There was some confusion around base configurations and when certain values should be used. Hopefully this clears some of that up. 
closes #40
> Update Base Examples To Be More Clear

- package.json
- yarn.lock
Updating a few deps for security.
> chore: Update Dependencies

- src/utils/ticketFinder/finders/jira/__tests__/finders.jira.test.js
- src/utils/ticketFinder/finders/jira/index.js
> fix: Dedupe Branch and Body Jira Tickets

- src/facades/ReleaseCommunicationFacade.js
- src/utils/ticketFinder/__tests__/ticketFinder.test.js
- src/utils/ticketFinder/finders/jira/index.js
related to #50 
We're hoping that the regex was off here, and that this shores up the issue.
> fix: Jira Branch Regex

- src/utils/__tests__/getTagDiffFromTagId.test.js
- src/utils/getTagDiffFromTagId.js
> fix: Global Regex Not Correctly Finding Tags

- .github/workflows/captains-test.yml
- .gitignore
- jest.config.js
- package.json
- src/connectors/GithubConnector/GithubConnectorV3.js
- src/connectors/GithubConnector/index.js
- src/constants/index.js
- src/facades/ReleaseCommunicationFacade.js
- src/factories/Message/__tests__/Message.test.js
- src/factories/Message/generate.js
- src/factories/Team/__tests__/Team.test.js
- src/handlers/postMessageHandler.js
- src/index.js
- src/utils/__tests__/formatMessages.test.js
- src/utils/__tests__/populateMessages.test.js
- src/utils/formatMessages.js
- src/utils/generateSlackFormatterUrl.js
- src/utils/populateMessages.js
- src/utils/ticketFinder/finders/github/index.js
- src/utils/ticketFinder/finders/jira/index.js
- src/utils/ticketFinder/index.js
- yarn.lock
✍️ Updating the repo to conform to prettier coding conventions.
🔍 Adds `lint-staged` so that we have everything covered before pushing to remote.
⏰ Added jest coverage of `75%` to start. You will no longer be able to push your code changes if tests fall below this threshold. 
This was updated in a previous pr and the repo never got the `prettier --write` treatment.
N/A
N/A
> chore: Repo Quality of Life Improvements

- README.md
- docs/README.md
- docs/configuration/README.md
- docs/contributing/README.md
- docs/examples/README.md
- src/utils/__tests__/initializeCaptainsConfig.test.js
- src/utils/initializeCaptainsConfig.js
closes #70 
closes #48 
We want to add support for Target's official CI system Vela.
> feat: Add First Class Vela Support

- yarn.lock
Dependabot found a minor security update that it could not create a PR for. This updates that dep to keep the repo up to date. 
Security deps
test pass
N/A
> chore: Update kind-of 6.0.3 security

- src/facades/ReleaseCommunicationFacade.js
Noticed a simple typo in #81, but couldn't leave a suggestion as it wasn't part of the diff.
> fix: typo, retreive -> retrieve

- .eslintignore
- src/utils/sendMessages.js
As proposed by @BRKalow in #81, we've moved to use "asserted order" for messages. It does indeed take longer, but that is okay to assert the order as that is far more important. 
N/A
N/A
> fix: Assert Message Order

- Dockerfile
Upgrading Jest caused a Node version mismatch:
The docker build subsequently failed. 
n/a
Yes, but manually with docker, see below picture.
> chore: Update Docker

- src/utils/ticketFinder/finders/github/__tests__/githubFinder.test.js
- src/utils/ticketFinder/finders/github/index.js
There was an issue found with the github regex. This has been here for some time now, but luckily the syntax provided found it. The blocks api actually threw an error for the incorrect URL, so we may have not found it without that. 
Fixes a regex issue. 
**Before**
**After**
> fix: Incorrect Github Regex

- src/handlers/postToPRHandler.js
Quick hotfix to fix undefined issue in comment block.
> fix: User Defined Body Should Not Be Undefined

- .eslintrc
- src/index.js
This PR adds better error handling for subchannel message sending. Right now we currently bomb out if there is no existing subchannels. This forces the application to continue to PR commenting and reports if there were any issues with that as well. 
^
> chore: Add Better Error Handling

- src/facades/__tests__/ReleaseCommunicationFacade.test.js
> fix: Lint Broken

- docs/.npmrc
- docs/yarn.lock
- yarn.lock
> chore: Update Deps

- docs/package.json
- docs/yarn.lock
upgrade doc site to docusaurus 2.1.0
use stable docusaurus
update deps
tested locally with `yarn start` and `yarn build` from `docs` folder
> fix(deps): upgrade docusaurus to 2.1.0

- .github/workflows/docker-publish.yml
directly pulled from https://github.com/target/karmabot/blob/master/.github/workflows/docker-image.yml
be able to release captains log
> ci: docker publish workflow

- .github/workflows/docker-publish.yml
> fix: job order
