target/captains-log

README.md, config/default.json, src/config.js, src/connectors/GithubConnector.js
This should allow people to pass in `PLUGIN_ENTERPRISE_HOST` as a value.
The only time people would want this feature is if they're working on a company Github. It's a different domain.
=> bug fix: More Flexible Github Connector

src/facades/ReleaseCommunicationFacade.js, src/facades/__fixtures__/pullRequestResponse.json, src/facades/__fixtures__/pullRequestResponseRawLink.json, src/facades/__tests__/ReleaseCommunicationFacade.test.js, src/factories/Message/__tests__/Message.test.js, src/factories/Message/index.js, src/factories/Team/__tests__/Team.test.js, src/factories/Team/index.js, src/index.js, src/utils/__tests__/populateMessages.test.js, src/utils/index.js, src/utils/populateMessages.js, src/utils/truncate.js
Right now we're showing `coming soon...` under the details section. Let's make that section more useful.
We scrape the title from the PR, and use that as a nice one-sentence description of each PR.
For my next trick ✨, you'll see a follow up PR that allows an optional `stripCommitType`. Then we can remove `feature:`, `bugfix:`, and the like if the user so chooses.
=> Feature: Details will show PR Titles

src/facades/ReleaseCommunicationFacade.js, src/facades/__fixtures__/pullRequestResponse.json, src/facades/__fixtures__/pullRequestResponseRawLink.json, src/facades/__tests__/ReleaseCommunicationFacade.test.js
We were not supporting team names like `JIRA2-1234` which is perfectly valid. This will allow teams to use any valid Jira name for their tickets.
=> fix: Jira Regex Should Support Numbers

src/factories/Team/__tests__/Team.test.js, src/factories/Team/index.js
There were some slight issues with formatting that were semi-expected. We'd set arbitrary limits on the wrap and truncate portions of our team `addMessage`. This has been addressed and all limits have been restricted even further. This should help format all messages on slack correctly and add white space where needed.
closes #20
=> Slack Formatting Whitespace Fix

src/utils/ticketFinder/__fixtures__/mockBody.js, src/utils/ticketFinder/finders/jira/index.js
Updates the default Jira issue regex to disallow leading numbers on project keys, and to require non-zero-prefixed issue numbers. This is customizable anyway in case anyone in the wild uses only numbers for their project key, but it's a more sane default with less false positives (such as `YYYY-MM` dates surrounded by brackets) that aligns more closely to [the apparent Jira default of requiring two uppercase letters](https://confluence.atlassian.com/display/JIRA041/Configuring+Project+Keys).
=> fix: update Jira issue regex to no leading number

src/utils/ticketFinder/__fixtures__/mockBody.js, src/utils/ticketFinder/__tests__/ticketFinder.test.js
Adds some additional tests for the Jira issue bracket syntax and also for the false positives prevented by #22.
=> test: add for jira brackets and false positives

src/index.js, src/utils/__tests__/generateSlackFormatterUrl.test.js, src/utils/generateSlackFormatterUrl.js, src/utils/index.js
closes #19
This was a great idea from @remoz. We were copy and pasting the attachments from the console to the browser to test if Captain's Log output was correct. This will make it so you can open up the Slack Message Formatter URL directly from console.
=> Add Slack Message Formatting Url To Console Output

docs/configuration/README.md
Updates the documentation site to add steps indicating how to get a user group ID for use in the mentions configuration.
=> docs: add steps to find group ID for mentions

.eslintrc, src/factories/Team/__tests__/Team.test.js, src/factories/Team/index.js
This was an oversight in the original design of the trackers. Instead of looking for a single match, we were looking to see if _everything_ matched. This isn't intended behavior when a team is using multiple trackers. 
Matchers will now look for any single match and mark the match as true.
closes #29
=> Fix: Multiple Issue Trackers Sending Message to Default

docs/configuration/README.md, docs/examples/README.md, package.json, src/connectors/SlackConnector.js, src/facades/ReleaseCommunicationFacade.js, src/factories/Team/__tests__/Team.test.js, src/factories/Team/index.js, src/handlers/postMessageHandler.js, src/index.js, yarn.lock
closes #38 
This feature allows users to designate one, or multiple, channels to send their teams section of Captain's Log to. 
These will only send when there are notes for that particular team, otherwise it will only send to the main Captain's Log channel.
=> Add Ability to Send Logs To Separate Channels

src/facades/ReleaseCommunicationFacade.js, src/facades/__tests__/ReleaseCommunicationFacade.test.js, src/index.js
When a pull request body was _empty_ it would leave `pr.body` as a `null` value. This would result in `TypeError: Cannot read property 'replace' of null` since it is not a string. We're just defaulting the value of `pr.body` to be an empty string here in that case. 
Also fixed: there was a non-breaking error when you would not list any `sub-teams` in your `.drone.yml` and it would result in `ERROR (...): Cannot read property 'length' of undefined`. This was fixed with a simple defaulting of the array.
=> Fix: Empty PR Body Error

docs/pr-body/README.md, src/facades/ReleaseCommunicationFacade.js, src/utils/ticketFinder/__tests__/ticketFinder.test.js, src/utils/ticketFinder/finders/github/__tests__/githubFinder.test.js, src/utils/ticketFinder/finders/github/index.js, src/utils/ticketFinder/finders/jira/index.js, src/utils/ticketFinder/index.js
This PR adds support for SCM integration with Jira. Jira has workflows that use a specific "branching convention" to associate github (and other SCM) pull requests to Jira tickets. That convention is outlined [here](https://confluence.atlassian.com/jirasoftwarecloud/referencing-issues-in-your-development-work-777002789.html).
Currently we're only supporting the `branch name` convention, if we receive asks for the commit convention we can modify CL to look at those as well. Ultimately we want to cut down on API calls to make sure our users do not exceed github api rate limits. 
closes #41
=> Jira Branch Name Convention Support

.gitignore, src/utils/ticketFinder/__tests__/ticketFinder.test.js, src/utils/ticketFinder/finders/jira/index.js
Remove unneded character in regex
=> More thorough tests of regex

docs/configuration/README.md, src/config.js, src/index.js
closes #54 
This adds a single field to the configuration called `slack_message_heading`. You can use this field to populate the Captain's Log heading with whatever you would like. 
Note: when #55 is merged, we'll need to update this pull request or have a subsequent pull request that will add this field to the external config.
=> feat: Add Custom Slack Heading

src/utils/__tests__/initializeCaptainsConfig.test.js, src/utils/initializeCaptainsConfig.js
Related to #54 
Just adding this to the `.captains.yml` that was added with #55.
=> Add New Slack Heading To .captains.yml

.eslintrc, .github/workflows/captains-test.yml, docs/configuration/README.md, src/config.js, src/utils/__tests__/initializeCaptainsConfig.test.js, src/utils/initializeCaptainsConfig.js
In #52 I broke using Captain's Log with a `.drone.yml` and ` .captains.yml`. This didn't impact anyone who didn't switch over, but for those who did, they were unable to receive release notes. 
Had I wrote the test that @jmccann so graciously asked me to write, this would have been caught. I should have listened 😄. The tests in this PR should cover us.
=> fix: Captains yml Broke

yarn.lock
Somehow Target dependencies got into the lock file. We needed to regen that whole file, so here it is.
=> chore: Remove Target Deps from Yarn Lock

src/utils/ticketFinder/finders/github/__tests__/githubFinder.test.js, src/utils/ticketFinder/finders/github/index.js
Enhances the GitHub URL regex to only match issue URLs rather than any GitHub URL with digits in the path, to support multiple subdomains for some companies, to not limit supported domain and owner and repo names to basic A-Z character set but to support other ASCII or Unicode characters, etc. - all while retaining the fix from #86, mostly by using a `[^\s]` pattern to avoid matching whitespace.
There were some false positives and some cases where existing regex wouldn't quite work.
Existing unit tests pass. Added some more unit tests that fail without the changes but pass with.
Without changes:
With changes:
=> refactor: enhance github url regex

src/utils/ticketFinder/finders/github/__tests__/githubFinder.test.js, src/utils/ticketFinder/finders/github/index.js
This PR adds case-insensitivity to the regular expression that looks for GitHub keywords (`Close(s)`, `Fix(es)`, `Resolve(s)`) in PR descriptions.
I noticed (I think) that we were possibly missing detection of capitalized GitHub keywords (`Close(s)`, `Fix(es)`, `Resolve(s)`). This [is supported by GitHub](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) so we should support it.
:x: Failing before:
✅ Passing after:
=> fix: support capitalized github keywords

src/handlers/postMessageHandler.js, src/index.js
#99 was supposed to fix the issues with error handling, but it turns out the errors were not bubbling as expected and we were still getting unhandled promise rejections. It was clear that we didn't need to bomb the process if the message sending failed, since we run a post to comment routine after posting. So this PR removes unnecessary error throwing and provides clearer messaging. 
^
=> fix: Subchannel Posting Should Not Error Entire Process

src/handlers/postMessageHandler.js
resolves https://github.com/target/captains-log/issues/115
I saw a slack token url secret being logged in CI after a task failed, so wanted to make sure we aren't logging secrets.
minor change in logging
=> fix: dont log channel url in error message

.github/workflows/docker-publish.yml
no tags are being added on merge to master so job is failing. i think we at least need `type=ref,event=branch`
=> ci: add tags
